### ISSUE TITLE
Not Getting All Diagrams

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/SCT_Parse#1]
Reference the ZLC SCT2 file:

It only parsed to 10211_ENV_VOR-DME RWY 26.txt

**Comment by Nikolai558** [comment]
Sector File has IAP Names that do not have any data attached to them, 
![image](https://user-images.githubusercontent.com/38259407/81632290-206cd600-93c7-11ea-9163-8063c1288aa3.png)

Will fix on next release to check for things like this.

**Comment by Nikolai558** [comment]
This has been fixed, See below for an example of what it does when it comes across this error.
![VersionFixExample](https://user-images.githubusercontent.com/38259407/81743078-53ae7400-945e-11ea-9688-f159ebe610bb.JPG)
