### ISSUE TITLE
No EXE

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/SCT_Parse#3]
**Describe the bug**
I no longer see an EXE. I remember it being in an EXE and your ReadMe mentions it being an EXE.

**Additional context**
I noticed that it is no longer picking up the "missing_data" ones from ZLC SCT2.

**Comment by Nikolai558** [comment]
Maybe a bug with github? 

![image](https://user-images.githubusercontent.com/38259407/83180561-d717c880-a0e0-11ea-8e74-58ccd9cf4c54.png)

There is an EXE there in the latest release. Am I missing something or was github being a bit glitchy?

**Comment by KSanders7070** [comment]
This was my mistake. All is good.
